name: "version-release"

on:
  push:
    tags:
      - 'v*'
      - 'zenstac-v*'

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: zenstac-v__VERSION__
          releaseName: "ZenSTAC v__VERSION__"
          releaseBody: |
            ## What's New in v__VERSION__
            
            ### Features
            - Initial release of ZenSTAC
            - STAC server functionality
            - Spatial data management
            
            ### Downloads
            - Windows: .exe or .msi installer
            - Linux: .deb, .AppImage, or .rpm package
            
            Built by Earthal Labs
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }} 